### ISSUE TITLE
Not possible to record vaccinations on the same day as the age matches exactly

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#53]
You cannot save the vaccinations on the same day the child is exactly that age. For example, I cannot record 2 month vaccinations when the child is exactly 2 months. Why is that occurring?

To replicate:
1. Log into the app
2. Use testing account and username: demo
3. Create a child with the exact age as vaccination - 2m (8w), 4m, 6m, or 9m (no extra days or weeks)
4. Try and add immunization for that day. You should not be able to

**Comment by ageryck** [comment]
@hilpitome did you find out anything here ? cc @msschroeder

**Comment by hilpitome** [comment]
Conducted tests and found out that the problem is occurring in unicef-tunisia as well.
The sample app in the child module does not have the same issue
The problem is not limited to children with an exact date. Conducted tests with children around 8 weeks old and discovered that:
- You cannot vaccinate a child from 8w to 8w 4 days old.
- You can only give the child the 8w vaccine from 8w 5 days onwards

**Comment by msschroeder** [comment]
@hilpitome Great! Thank you so much for the feedback. Is this something that can be easily fixed?

**Comment by hilpitome** [comment]
@msschroeder I am working with @ellykits to try and find where the problem is. Once we find the configuration or piece of logic that is causing this the solution should be quick.
